[molecules]
x = "x_location"
y = "y_location"
z = "z_location"
gene = "feature_name"
qv = "qv"
min_molecules_per_gene = 10
exclude_genes = "NegControl*,BLANK_*,antisense_*"
min_molecules_per_cell = 50

[prior]
unassigned_label = "UNASSIGNED"

[segmentation]
prior_segmentation_confidence = 0.5

